get_schedule:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: wanas
    refresh:
      default: false
      selector:
        boolean:

set_schedule:
  fields:
    config_entry_id:
      selector:
        config_entry:
          integration: wanas
    days:
      required: true
      example: '["monday", "tuesday"]'
      selector:
        select:
          multiple: true
          translation_key: day
          options:
            - sunday
            - monday
            - tuesday
            - wednesday
            - thursday
            - friday
            - saturday
    periods:
      required: true
      example: >-
        [{"until": "06:00", "speed": 1, "temperature": 18},
        {"until": "07:00", "speed": 2, "temperature": 20},
        {"until": "14:00", "speed": 1, "temperature": 20},
        {"until": "15:00", "speed": 3, "temperature": 20},
        {"speed": 1, "temperature": 18}]
      selector:
        object:
